version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.2.14
    - 5.2.9
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.8
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.8
  - dependency-name: next
    versions:
    - 10.1.1
    - 10.1.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.19.0
    - 4.20.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
